### PR TITLE
Update DeployBot.php

### LINKED ISSUE #6: Guzzle fails to send headers and requests to incorrect URL
Using Guzzle 6.3.3, the headers fail to send.

I resolved by using my own Guzzle Client in the constructor like so:

```php
$dbot = new DeployBot($this->settings['deploybot']['key'], $this->settings['deploybot']['user'],
	new Client([
		'base_uri' => "https://" . $this->settings['deploybot']['user'] . ".deploybot.com/api/v1/",
		'headers'  => [
			'X-Api-Token' => $this->settings['deploybot']['key'],
			'Accept'      => 'application/json',
		]
	])
);
```

Notice use of `base_uri` instead of `base_url` and moving the headers up to the root element (no `defaults`) needed.

### PR DESCRIPTION
**Pull request by jarrodbell**
Fixes #6

### CODE REVIEW

**Comment by JayBizzle** [comment]
:heart:

**Comment by JayBizzle** [comment]
Just realised i haven't published a new release yet.

Do you think this requires a whole new version release, i.e. `v3.0.0` as it may not be backwards compatible i think, although i'm still not quite sure when Guzzle changed to break this as the last release of Guzzle on the v6 branch was over a year ago and I can't believe it has been broken for that long https://github.com/guzzle/guzzle/releases/tag/6.3.3

/ping @jarrodbell

**Comment by jarrodbell** [comment]
Your composer requires Guzzle ^6.0, so shouldn't break anyones installs if you do a minor update. I'm surprised the code worked at all with Guzzle 6 branch actually, as both `base_url` was changed to `base_uri` and the `defaults` array was [moved up a level](https://github.com/guzzle/guzzle/commit/129e153750627a0c61fbfbd1802a396188a77259) in Guzzle 6.0

**Comment by JayBizzle** [comment]
Yeah, this has puzzled me a little as I am pretty sure this worked at some point using Guzzle 6, but looking through their code, I also can't see how that was the case.

Anyway, I'm going to release this as version 2.1

Thanks for your input 👍

**Pull request merged**
